apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: abc-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: abc-app
spec:
  source:
    git:
      url: https://github.com/ciberkleid/abc-app
      ref:
        branch: main
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: asaikali 
  - name: gitops_repository_name
    value: tap-run-gitops
  - name: gitops_ssh_secret
    value: git-ssh